name: nero
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.8.9
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  get: 4.6.5
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  sms_autofill: ^2.2.0
  timer_count_down: ^2.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/
  uses-material-design: true
